# fly.toml app configuration file generated for bonvoyagea on 2024-03-01T16:12:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bonvoyage'
primary_region = 'lhr'

[build]
  image = 'duli1224/bonvoyage:latest'

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "211463545556344"
  Cloudinary__CloudName = "dnc4mirm7"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
